### ISSUE TITLE
Working ?

### ISSUE THREAD

**Issue by AxisLTD** [ValvojaX/csgo_items_parser#1]
is it working now

**Comment by AxisLTD** [comment]
because these links do not work


        self.items_game_url = 'https://raw.githubusercontent.com/SteamDatabase/GameTracking-CSGO/master/csgo/scripts/items/items_game.txt'
        self.items_game_cdn_url = 'https://raw.githubusercontent.com/SteamDatabase/GameTracking-CSGO/master/csgo/scripts/items/items_game_cdn.txt'
        self.csgo_english_url = 'https://raw.githubusercontent.com/SteamDatabase/GameTracking-CSGO/master/csgo/resource/csgo_english.txt'
        self.schema_url = 'https://raw.githubusercontent.com/SteamDatabase/SteamTracking/b5cba7a22ab899d6d423380cff21cec707b7c947/ItemSchema/CounterStrikeGlobalOffensive.json'

**Comment by ValvojaX** [comment]
> because these links do not work

You are correct, seems like latest version doesn't have those files anymore. Temporary fix is to replace the links with the last commit that had the files.

**Comment by AxisLTD** [comment]
so how can i do this :/

**Comment by ValvojaX** [comment]
> so how can i do this :/

I replaced the links to use the previous commit. Should be working now.
